### ISSUE TITLE
NPE on console faction disband

### ISSUE THREAD

**Issue by melluh** [ProSavage/SavageFactions#175]
**Describe the bug**
A NPE is thrown when a faction is disbanded by the console.
https://paste.md-5.net/uwifebejun.bash

**To Reproduce**
1. Install version mentioned below
2. Create a faction
3. Attempt to disband the faction via console

**Server Version (please complete the following information):**
- Spigot Version: Spigot 1.8.8
- Factions Version: 1.6.9.5-U0.2.1-RC-1.4-STABLE

**Comment by prosavage** [comment]
You're using an outdated version, reopen this issue if the problem persists with 1.6-RC-2

**Comment by melluh** [comment]
@ProSavage I can't reopen the issue, but the problem is still present on v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.
https://paste.md-5.net/oboyapaziw.bash

**Comment by redstonedesigner** [comment]
Issue reopened per request of user.

**Comment by prosavage** [comment]
I fixed it in https://github.com/SavageLLC/SavageFactions/commit/331eab414bd64015e68b954fc68bae2cfed19743

Just referenced the wrong number, so github didnt close it.

**Comment by melluh** [comment]
Please reopen, the issue is still present. Just on a different line now.
https://paste.md-5.net/esoyedasen.bash

**Comment by prosavage** [comment]
Its fixed now.
